# Generated by Django 5.2.3 on 2025-06-24 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_faculty_delete_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Faculties'},
        ),
    ]
